export const DEFAULTS = {
  name: 'Someone Special',
  quote: 'Some people become special without even trying ✨',
  quoteSub: 'Wanna see a little creativity of mine?',
  letter: `I know it's not that much I can do😔, it's a simple way to celebrate your birthday (sorry about that💔). I know I'm a bad friend, so sorry if I ever said or did something that made you sad and you kept hiding it😓. I'm not gonna lie, you are my best online friend... I'm really glad for the time when we met each other🥹🤍. So yesss it's YOUR BIRTHDAY anyway✨. I really wish I was with you in reality celebrating with you and making the BEST (WORST 😂) cake ever 😭🫡💗🎂🎉`,
  from: '— Your Friend 🤍',
  finalMsg: `You deserve all the happiness in the world today and every day. No matter how far, you'll always have a friend cheering for you. Happy birthday, truly 🎂🤍`,
  theme: '',
  adminPw: '',
  showPrank: true,
  prankIntensity: 'high',
  photos: [],
  musicUrl: '',
  secretMessage: 'You are truly special. Wishing you happiness always ❤️',
};
